# TrajectoryPlannerROS:
#   acc_lim_x: 1.0
#   acc_lim_y: 1.0
#   acc_lim_theta: 2.0

#   max_vel_x: 0.4
#   min_vel_x: -0.4
#   max_vel_y: 0.4
#   min_vel_y: -0.4

#   max_vel_theta: 1.0
#   min_vel_theta: -1.0

#   xy_goal_tolerance: 0.2
#   yaw_goal_tolerance: 0.1

#   sim_time: 1.5
#   sim_granularity: 0.025
#   vx_samples: 10
#   vy_samples: 10
#   vtheta_samples: 20

#   controller_frequency: 10.0
  
TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_y: 0.5
  min_vel_y: 0.1
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.3

  acc_lim_theta: 0.25
  acc_lim_x: 0.25
  acc_lim_y: 0.25

  holonomic_robot: true