TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_y: 0.5
  min_vel_y: 0.1
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.3

  acc_lim_theta: 0.25
  acc_lim_x: 0.25
  acc_lim_y: 0.25

  holonomic_robot: true
