# global_frame: "map"
# robot_base_frame: "base_link"

# footprint: [[-0.3, -0.225], [-0.3, 0.225], [0.3, 0.225], [0.3, -0.225]]
# inflation_radius: 0.5

# update_frequency: 1.0
# publish_frequency: 1.0
# transform_tolerance: 0.5

# static_map: false
# rolling_window: false

# obstacle_layer:
#   enabled: true
#   obstacle_range: 2.5
#   raytrace_range: 3.0
#   track_unknown_space: false
#   observation_sources: scan
#   scan:
#     topic: /scan
#     sensor_frame: base_link
#     data_type: LaserScan
#     clearing: true
#     marking: true

# inflation_layer:
#   enabled: true
#   inflation_radius: 0.5

global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: true
