# global_frame: "map"
# robot_base_frame: "base_link"

# footprint: [[-0.3, -0.225], [-0.3, 0.225], [0.3, 0.225], [0.3, -0.225]]
# inflation_radius: 0.5

# update_frequency: 5.0
# publish_frequency: 5.0
# transform_tolerance: 0.5

# static_map: false
# rolling_window: true
# width: 3.0
# height: 3.0
# resolution: 0.05

# obstacle_layer:
#   enabled: true
#   obstacle_range: 2.5
#   raytrace_range: 3.0
#   observation_sources: scan
#   scan:
#     topic: /scan
#     sensor_frame: base_link
#     data_type: LaserScan
#     clearing: true
#     marking: true

# inflation_layer:
#   enabled: true
#   inflation_radius: 0.5

local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
